# Generated by Django 5.2.6 on 2025-10-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
